version: '3'

services:
  webdav:
    image: twizzel/webdav
    container_name: wevdav_container
    restart: always
    ports:
      - "8080:80"
    environment:
      AUTH_TYPE: Digest
      USERNAME: example
      PASSWORD: example
    volumes:
      - ${MY_DAV}:/var/lib/dav

